# Important: ensure this source is specified in the Podfile
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImmutableX' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImmutableX
  pod 'ImmutableXCore'
  pod 'ImmutableXWalletSDK'

  target 'ImmutableXTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ImmutableXUITests' do
    # Pods for testing
  end

end
